version: "2"
services:
  condor:
    build: condor
    image: condor
    ports: 
      - "9618:9618"
      - "40000-40500:40000-40500"
    hostname: $HOSTNAME
    privileged: true
    tty: true
    stdin_open: true
    networks:
      cs_net:
        ipv4_address: 172.28.5.2        
    mem_limit: 5M

networks:
  cs_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16



